### PR TITLE
Fix `static mut` issues with routines

### LINKED ISSUE #661: Fix compilation warnings for shared reference to mutable static
With recent versions of stable Rust, we now get a bunch of compilation warnings like:

```
warning: creating a shared reference to mutable static is discouraged
    --> crates/ark/src/interface.rs:1953:31
     |
1953 |             unsafe { Rf_error(ERROR_BUF.as_ref().unwrap().as_ptr()) };
     |                               ^^^^^^^^^^^^^^^^^^ shared reference to mutable static
     |
     = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
     = note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives
```

### PR DESCRIPTION
**Pull request by lionel-**
Closes #661.

Ideally `R_ROUTINES` would be thread-local but that's currently inconvenient in unit tests.

### CODE REVIEW

File: crates/harp/src/routines.rs [hunk 1]
```diff
@@ -27,16 +41,24 @@ pub unsafe fn r_register_routines() {
...
         numArgs: 0,
     });
 
+    // Now unwrap the definitions from our thread-safe type
+    let unwrapped: Vec<R_CallMethodDef> = R_ROUTINES
+        .lock()
+        .unwrap()
+        .iter()
+        .map(|def| def.inner)
+        .collect();
```
Comment (DavisVaughan) [inline crates/harp/src/routines.rs:56]: I'm fairly surprised you dont get a warning about "dropping temporary value" since no one is holding the lock in a local variable here. I seem to get that all the time when doing stuff like this.

File: crates/harp/src/routines.rs [hunk 2]
```diff
@@ -27,16 +41,24 @@ pub unsafe fn r_register_routines() {
...
     // Make sure we have an "empty" routine at the end.
-    R_ROUTINES.push(R_CallMethodDef {
+    add(R_CallMethodDef {
         name: std::ptr::null(),
         fun: None,
         numArgs: 0,
     });
 
+    // Now unwrap the definitions from our thread-safe type
+    let unwrapped: Vec<R_CallMethodDef> = R_ROUTINES
```
Comment (DavisVaughan) [inline crates/harp/src/routines.rs:51]:
```suggestion
    let routines: Vec<R_CallMethodDef> = R_ROUTINES
```

File: crates/harp/src/routines.rs [hunk 3]
```diff
@@ -27,16 +41,24 @@ pub unsafe fn r_register_routines() {
...
+        .unwrap()
+        .iter()
+        .map(|def| def.inner)
+        .collect();
+
     R_registerRoutines(
         info,
         std::ptr::null(),
-        R_ROUTINES.as_ptr(),
+        unwrapped.as_ptr(),
```
Comment (DavisVaughan) [inline crates/harp/src/routines.rs:61]:
```suggestion
        routines.as_ptr(),
```

File: crates/harp/src/routines.rs [hunk 4]
```diff
@@ -5,18 +5,32 @@
...
+// Sync and Send wrapper that we can store in a global. Necessary because
+// `R_CallMethodDef` includes raw pointers.
+struct CallMethodDef {
+    inner: R_CallMethodDef,
+}
+
+unsafe impl Send for CallMethodDef {}
+unsafe impl Sync for CallMethodDef {}
+
+static R_ROUTINES: Mutex<Vec<CallMethodDef>> = Mutex::new(vec![]);
```
Comment (DavisVaughan) [inline crates/harp/src/routines.rs:24]: Nice I also tried this when fiddling with this one last week but got stuck on the `R_CallMethodDef` not being send+sync problem

File: crates/harp/src/routines.rs [hunk 5]
```diff
@@ -5,18 +5,32 @@
...
 
-static mut R_ROUTINES: Vec<R_CallMethodDef> = vec![];
+// Sync and Send wrapper that we can store in a global. Necessary because
+// `R_CallMethodDef` includes raw pointers.
+struct CallMethodDef {
+    inner: R_CallMethodDef,
+}
+
+unsafe impl Send for CallMethodDef {}
+unsafe impl Sync for CallMethodDef {}
```
Comment (DavisVaughan) [inline crates/harp/src/routines.rs:22]: I think my main comment is that `#[harp::register]` is pretty freaking magical. It generates some code that runs _at application startup time_ in an OS specific way. 

I guess we can assume that code is always run on a single thread? I have no idea how startup code gets run on a per OS basis. I just want to make sure this doesn't screw us up.

**Review by DavisVaughan — APPROVED** [review]

File: crates/harp/src/routines.rs (hunk 5 above)
Comment (lionel-) [reply crates/harp/src/routines.rs:22]: We're just saying it is fine to send these raw pointers across threads, which it is as long as you don't do anything with them. We're not introducing any new area of unsafety AFAICT.
